### ISSUE TITLE
errors on first call of await hubConnection.StartAsync();

### ISSUE THREAD

**Issue by AnthonyEmiom** [carlfranklin/AvnAudio#1]
When I run the Client from visual Studio the first time through index.html

Line 69:             await hubConnection.StartAsync();

Clicking [Enumerate Devices]

crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Response status code does not indicate success: 405 (Method Not Allowed).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 405 (Method Not Allowed).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.AspNetCore.Http.Connections.Client.HttpConnection.NegotiateAsync(Uri url, HttpClient httpClient, ILogger logger, CancellationToken cancellationToken)
   
   I'm running latest .net 7.0 VS 2022.
   
   The software seems to run but I get the bar at the bottom.
   
![Screenshot 2023-11-06 at 17 55 41](https://github.com/carlfranklin/AvnAudio/assets/137493720/0dde4c58-6e8c-412a-be1d-8beef5c17e95)

Running unchanged as downloaded.

Ps. Thanks for this code and the .Net Rocks Podcast!

**Comment by AnthonyEmiom** [comment]
Duh....... my fault setting the Client project to start on run debug instead of Server.... at least I think thats the cause I made some other small ordering changes too. Happy days!
